name: Publish-Crate-Upon-Release
on:
  release:
    types: [published]

jobs:
  publish-automatically:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Rustup
        run: |
          rustup install stable
          rustup override set stable

      - name: publish crates
        run: cargo publish --token ${{ secrets.CARGO_API_TOKEN }}
