on: [workflow_dispatch]

name: Conformance Suite

jobs:
  conformance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Rustup
        run: |
          rustup install --profile minimal stable
          rustup override set stable
      - run: |
          cargo build --manifest-path=tests/conformance/Cargo.toml
      - uses: sigstore/sigstore-conformance@main
        with:
          entrypoint: ${{ github.workspace }}/tests/conformance/target/debug/sigstore
